[package]
name = "choreo_components"
version = "0.1.0"
edition = "2024"

[dependencies]
choreo_models = { path = "../choreo_models" }
choreo_master_mobile_json = { path = "../choreo_master_mobile_json" }
env_logger = "0.11"
log = "0.4"
rodio = "0.21.1"
