[package]
name = "choreo_components"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
choreo_models = { path = "../choreo_models" }
choreo_master_mobile_json = { path = "../choreo_master_mobile_json" }
choreo_i18n = { path = "../choreo_i18n" }
choreo_state_machine = { path = "../choreo_state_machine" }
crossbeam-channel = "0.5"
log = "0.4"
slint = "1.14.1"
material-color-utilities = "1.0.0-dev.18"
nject = "0.4.5"
time = "0.3.46"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dirs = "5.0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Storage", "Window"] }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
ndk-context = "0.1"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2"

[build-dependencies]
slint-build = "1.14.1"

[dev-dependencies]
rspec = "1.0.0"
