[package]
name = "rchoreo_wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
slint = "1.14"
shared = { path = "../../crates/shared", package = "rchoreo_shared" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
