[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C",
    "link-arg=/STACK:8388608" # increases the stack size to 8 MiB (= 8,388,608 bytes)
]

[target.aarch64-pc-windows-msvc]
rustflags = [
    "-C",
    "link-arg=/STACK:8388608" # increases the stack size to 8 MiB
]