[ui]
stack_size_bytes = 8388608

#[target.x86_64-pc-windows-msvc]
#rustflags = [
#    "-C",
#    "link-arg=/STACK:8388608"
#]

#[target.aarch64-pc-windows-msvc]
#rustflags = [
#    "-C",
#    "link-arg=/STACK:8388608"
#]