[package]
name = "rchoreo_android_egui"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
egui = "0.32.3"
egui-material3 = "0.0.7"
choreo_components_egui = { path = "../../crates/choreo_components_egui" }
